[build]
  functions = "netlify/functions"
  publish = "."

# Netlify Functions configuration
[functions]
  # 関数のタイムアウトを延長
  timeout = 30

# リダイレクト設定
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api?path=:splat"
  status = 200

# CORS Headers for static files
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"